-- MySQL Script generated by MySQL Workbench
-- Thu 14 Feb 2019 02:18:33 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ncct_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ncct_db` ;

-- -----------------------------------------------------
-- Schema ncct_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ncct_db` DEFAULT CHARACTER SET utf8 ;
USE `ncct_db` ;

-- -----------------------------------------------------
-- Table `ncct_db`.`application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`application` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`application` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ncct_db`.`batch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`batch` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`batch` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `estimated_delivery_date` DATE NOT NULL,
  `number_samples` INT NOT NULL,
  `experiment_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_batch_experiment2_idx` (`experiment_id` ASC) ,
  CONSTRAINT `fk_batch_experiment2`
    FOREIGN KEY (`experiment_id`)
    REFERENCES `ncct_db`.`experiment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ncct_db`.`classification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`classification` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`classification` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `classification_UNIQUE` (`name` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ncct_db`.`experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`experiment` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`experiment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number_of_samples` INT NOT NULL,
  `coverage` VARCHAR(45) NOT NULL,
  `costs` DECIMAL NOT NULL,
  `genome_size` VARCHAR(45) NOT NULL,
  `material_id` INT UNSIGNED NOT NULL,
  `species_id` INT UNSIGNED NOT NULL,
  `technology_type_id` INT UNSIGNED NOT NULL,
  `application_id` INT UNSIGNED NOT NULL,
  `nucleic_acid_id` INT UNSIGNED NOT NULL,
  `library_id` INT UNSIGNED NOT NULL,
  `project_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_experiment_material1_idx` (`material_id` ASC) ,
  INDEX `fk_experiment_species1_idx` (`species_id` ASC) ,
  INDEX `fk_experiment_technology_type1_idx` (`technology_type_id` ASC) ,
  INDEX `fk_experiment_technology_instrument1_idx` (`application_id` ASC) ,
  INDEX `fk_experiment_nucleic_acid1_idx` (`nucleic_acid_id` ASC) ,
  INDEX `fk_experiment_library1_idx` (`library_id` ASC) ,
  INDEX `fk_experiment_project1_idx` (`project_id` ASC) ,
  CONSTRAINT `fk_experiment_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `ncct_db`.`material` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_experiment_species1`
    FOREIGN KEY (`species_id`)
    REFERENCES `ncct_db`.`species` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_experiment_technology_type1`
    FOREIGN KEY (`technology_type_id`)
    REFERENCES `ncct_db`.`technology_type` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_experiment_technology_instrument1`
    FOREIGN KEY (`application_id`)
    REFERENCES `ncct_db`.`application` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_experiment_nucleic_acid1`
    FOREIGN KEY (`nucleic_acid_id`)
    REFERENCES `ncct_db`.`nucleic_acid` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_experiment_library1`
    FOREIGN KEY (`library_id`)
    REFERENCES `ncct_db`.`library` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_experiment_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `ncct_db`.`project` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ncct_db`.`library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`library` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`library` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ncct_db`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`material` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`material` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) );


-- -----------------------------------------------------
-- Table `ncct_db`.`nucleic_acid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`nucleic_acid` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`nucleic_acid` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ncct_db`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`person` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`person` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `institution` VARCHAR(100) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phonenumber` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ncct_db`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`project` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`project` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qbic_id` VARCHAR(10) NOT NULL,
  `dfg_id` VARCHAR(50) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `total_cost` DECIMAL NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `declaration_of_intent` MEDIUMBLOB NULL,
  `keywords` VARCHAR(100) NOT NULL,
  `sequencing_aim` VARCHAR(1000) NOT NULL,
  `contact_person_id` INT UNSIGNED NOT NULL,
  `topical_assignment_id` INT UNSIGNED NOT NULL,
  `classification_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_contact_person1_idx` (`contact_person_id` ASC) ,
  UNIQUE INDEX `dfg_id_UNIQUE` (`dfg_id` ASC) ,
  UNIQUE INDEX `qbic_id_UNIQUE` (`qbic_id` ASC) ,
  INDEX `fk_project_topical_assignments1_idx` (`topical_assignment_id` ASC) ,
  INDEX `fk_project_classification1_idx` (`classification_id` ASC) ,
  CONSTRAINT `fk_project_contact_person1`
    FOREIGN KEY (`contact_person_id`)
    REFERENCES `ncct_db`.`person` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_project_topical_assignments1`
    FOREIGN KEY (`topical_assignment_id`)
    REFERENCES `ncct_db`.`topical_assignment` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_project_classification1`
    FOREIGN KEY (`classification_id`)
    REFERENCES `ncct_db`.`classification` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `ncct_db`.`project_has_applicants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`project_has_applicants` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`project_has_applicants` (
  `project_id` INT UNSIGNED NOT NULL,
  `applicant_id` INT UNSIGNED NOT NULL,
  INDEX `fk_applicants_has_project_project1_idx` (`project_id` ASC) ,
  INDEX `fk_applicants_has_project_contact_person1_idx` (`applicant_id` ASC) ,
  CONSTRAINT `fk_applicants_has_project_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `ncct_db`.`project` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_applicants_has_project_contact_person1`
    FOREIGN KEY (`applicant_id`)
    REFERENCES `ncct_db`.`person` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ncct_db`.`project_has_cooperation_partners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`project_has_cooperation_partners` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`project_has_cooperation_partners` (
  `project_id` INT UNSIGNED NOT NULL,
  `cooperation_partner_id` INT UNSIGNED NOT NULL,
  INDEX `fk_project_has_cooperation_partners_project1_idx` (`project_id` ASC) ,
  INDEX `fk_project_has_cooperation_partners_contact_person1_idx` (`cooperation_partner_id` ASC) ,
  CONSTRAINT `fk_project_has_cooperation_partners_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `ncct_db`.`project` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_project_has_cooperation_partners_contact_person1`
    FOREIGN KEY (`cooperation_partner_id`)
    REFERENCES `ncct_db`.`person` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `ncct_db`.`species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`species` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`species` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ncct_db`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`table1` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ncct_db`.`technology_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`technology_type` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`technology_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ncct_db`.`topical_assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ncct_db`.`topical_assignment` ;

CREATE TABLE IF NOT EXISTS `ncct_db`.`topical_assignment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(6) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) );


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ncct_db`.`application`
-- -----------------------------------------------------
START TRANSACTION;
USE `ncct_db`;
INSERT INTO `ncct_db`.`application` (`id`, `name`) VALUES (1, '16S');
INSERT INTO `ncct_db`.`application` (`id`, `name`) VALUES (2, 'Metagenome');
INSERT INTO `ncct_db`.`application` (`id`, `name`) VALUES (3, 'Whole Genome');
INSERT INTO `ncct_db`.`application` (`id`, `name`) VALUES (4, 'Whole Exome');
INSERT INTO `ncct_db`.`application` (`id`, `name`) VALUES (5, 'Targeted Resequencing');
INSERT INTO `ncct_db`.`application` (`id`, `name`) VALUES (6, 'Epigenetics');
INSERT INTO `ncct_db`.`application` (`id`, `name`) VALUES (7, 'Whole Transcriptome');
INSERT INTO `ncct_db`.`application` (`id`, `name`) VALUES (8, 'mRNA');
INSERT INTO `ncct_db`.`application` (`id`, `name`) VALUES (9, 'sRNA');
INSERT INTO `ncct_db`.`application` (`id`, `name`) VALUES (10, 'Other');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ncct_db`.`classification`
-- -----------------------------------------------------
START TRANSACTION;
USE `ncct_db`;
INSERT INTO `ncct_db`.`classification` (`id`, `name`) VALUES (1, 'S1');
INSERT INTO `ncct_db`.`classification` (`id`, `name`) VALUES (2, 'S2');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ncct_db`.`library`
-- -----------------------------------------------------
START TRANSACTION;
USE `ncct_db`;
INSERT INTO `ncct_db`.`library` (`id`, `name`) VALUES (1, 'Illumina SBS');
INSERT INTO `ncct_db`.`library` (`id`, `name`) VALUES (2, 'PacBio SMRT');
INSERT INTO `ncct_db`.`library` (`id`, `name`) VALUES (3, 'Oxford Nanopore Technology');
INSERT INTO `ncct_db`.`library` (`id`, `name`) VALUES (4, 'MGI/BGI');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ncct_db`.`material`
-- -----------------------------------------------------
START TRANSACTION;
USE `ncct_db`;
INSERT INTO `ncct_db`.`material` (`id`, `name`) VALUES (1, 'Isolated nuclein');
INSERT INTO `ncct_db`.`material` (`id`, `name`) VALUES (2, 'Bacterial culture');
INSERT INTO `ncct_db`.`material` (`id`, `name`) VALUES (3, 'Soil');
INSERT INTO `ncct_db`.`material` (`id`, `name`) VALUES (4, 'Tissue');
INSERT INTO `ncct_db`.`material` (`id`, `name`) VALUES (5, 'Faeces');
INSERT INTO `ncct_db`.`material` (`id`, `name`) VALUES (6, 'Other');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ncct_db`.`nucleic_acid`
-- -----------------------------------------------------
START TRANSACTION;
USE `ncct_db`;
INSERT INTO `ncct_db`.`nucleic_acid` (`id`, `name`) VALUES (1, 'DNA');
INSERT INTO `ncct_db`.`nucleic_acid` (`id`, `name`) VALUES (2, 'RNA');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ncct_db`.`species`
-- -----------------------------------------------------
START TRANSACTION;
USE `ncct_db`;
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (1, 'Pseudomonas aeruginosa');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (2, 'Pectobacterium carotovorum subsp. carotovorum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (3, 'Escherichia coli');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (4, 'Shigella flexneri');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (5, 'Synechocystis sp. PCC 6803');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (6, 'Staphylococcus aureus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (7, 'Staphylococcus epidermidis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (8, 'Streptomyces coelicolor');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (9, 'Streptomyces lividans');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (10, 'Dianthus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (11, 'Silene');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (12, 'Theobroma cacao');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (13, 'Arabidopsis thaliana');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (14, 'Brassica napus subsp. rapifera');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (15, 'Brassica oleracea');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (16, 'Brassica oleracea var. viridis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (17, 'Brassica oleracea var. alboglabra');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (18, 'Brassica oleracea var. botrytis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (19, 'Brassica oleracea var. capitata');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (20, 'Malus domestica');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (21, 'Glycine max');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (22, 'Solanum lycopersicum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (23, 'Solanum tuberosum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (24, 'Cuscuta reflexa');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (25, 'Ambrosia artemisiifolia');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (26, 'Lolium perenne');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (27, 'Oryza sativa');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (28, 'Sorghum bicolor');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (29, 'Zea mays');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (30, 'Vaccinia virus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (31, 'Allium ampeloprasum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (32, 'Asparagus officinalis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (33, 'Schizosaccharomyces pombe');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (34, 'Schizosaccharomyces japonicus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (35, 'Saccharomyces cerevisiae');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (36, 'Caenorhabditis elegans');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (37, 'Daphnia pulex');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (38, 'Brachypodium distachyon');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (39, 'Galleria mellonella');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (40, 'Drosophila melanogaster');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (41, 'Danio rerio');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (42, 'Cichlidae');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (43, 'Haplochromis burtoni');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (44, 'Gallus Gallus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (45, 'Macaca mulatta');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (46, 'Homo sapiens');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (47, 'Canis lupus familiaris');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (48, 'Gluconobacter oxydans 621H');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (49, 'Equus caballus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (50, 'Methanocaldococcus jannaschii');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (51, 'Sus scrofa');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (52, 'Bos taurus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (53, 'Bos indicus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (54, 'Capra hircus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (55, 'Apis mellifera');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (56, 'Melipona quadrifasciata');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (57, 'Ovis aries');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (58, 'Mus musculus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (59, 'Rattus norvegicus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (60, 'Enterobacteria phage phiX174');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (61, 'Forficula auricularia');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (62, 'Corylus spp.');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (63, 'Corylus avellana');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (64, 'Juglans nigra');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (65, 'Kluyveromyces lactis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (66, 'Vitis vinifera');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (67, 'Carya illinoiensis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (68, 'Unidentified');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (69, 'Daphnia Magna');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (70, 'Tuber uncinatum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (71, 'Brassica oleracea var. italica');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (72, 'Cavia aperea');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (73, 'Tuber melanosporum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (74, 'Oryza sativa japonica');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (75, 'Tuber magnatum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (76, 'Tuber borchii');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (77, 'Apis mellifera mellifera');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (78, 'Juglans regia');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (79, 'Tuber indicum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (80, 'Tuber himalayense');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (81, 'Burkholderia thailandensis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (82, 'Tuber aestivum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (83, 'Tuber brumale');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (84, 'Amphilophus (nicaraguan)');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (85, 'Pythium aphanidermatum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (86, 'Streptomyces hawaiiensis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (87, 'Rosa wichurana');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (88, 'Mycobacterium tuberculosis strain H37Rv');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (89, 'Juglans ailantifolia');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (90, 'Juglans cinerea');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (91, 'Juglans major');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (92, 'Juglans microcarpa');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (93, 'Juglans regia x Juglans nigra');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (94, 'Staphylococcus aureus strain NCTC 8325');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (95, 'Salmonella enterica subsp. enterica serovar Typhimurium str. LT2');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (96, 'Brassica oleracea var. oleracea');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (97, 'Brassica oleracea var. gongylodes');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (98, 'Corylus maxima');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (99, 'Brassica napus var. napus Rapeseed');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (100, 'Methanothermobacter thermautotrophicus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (101, 'Brassica oleracea var. ramosa');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (102, 'Brassica oleracea var. medullosa');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (103, 'Brassica oleracea var. gemmifera');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (104, 'Caulobacter crescentus CB15');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (105, 'Amycolatopsis japonica');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (106, 'Anabaena sp. PCC 7120 (Nostoc sp. PCC 7120)');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (107, 'Anabaena variabilis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (108, 'Pseudomonas aeruginosa strain PAO1');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (109, 'Pseudomonas fluorescens SBW25');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (110, 'Monodelphis domestica');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (111, 'Salmonella enterica subsp. enterica serovar Typhimurium str. SL1344');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (112, 'Legionella pneumophila');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (113, 'Bacillus cereus strain ATCC 10987');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (114, 'Bacillus subtilis strain 168');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (115, 'Pasteuria ramosa');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (116, 'Cupriavidus metallidurans CH34');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (117, 'Rhodobacter sphaeroides strain 2.4.1');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (118, 'Macrostomum lignano');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (119, 'Candidatus Caldiarchaeum subterraneum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (120, 'Escherichia coli strain K12 DH10B');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (121, 'Human papillomavirus type 16');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (122, 'Tuber sinense');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (123, 'Ralstonia eutropha H16');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (124, 'Escherichia coli O157:H7 Sakai');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (125, 'Metagenomes');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (126, 'Brassica oleracea var. costata');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (127, 'Sorangium cellulosum strain So ce 56');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (128, 'Microcystis aeruginosa NIES-44');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (129, 'Microcystis aeruginosa NIES-843');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (130, 'Gasterosteus aculeatus aculeatus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (131, 'Escherichia coli strain K12 MG1655');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (132, 'Caulobacter crescentus NA1000');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (133, 'Brassica oleracea var. sabauda');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (134, 'Pseudomonas aeruginosa RP73');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (135, 'Brassica oleracea var. albiflora');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (136, 'Mus musculus polyomavirus 1');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (137, 'Tuber sp.');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (138, 'Salpiglossis sinuata');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (139, 'Vinca major');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (140, 'Nerium oleander');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (141, 'Nicotiana tabacum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (142, 'Nicotiana benthamiana');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (143, 'Lavandula canariensis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (144, 'Sanicula odorata');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (145, 'Helichrysum arenarium');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (146, 'Nicotiana longiflora');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (147, 'Achillea millefolium');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (148, 'Salvia officinalis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (149, 'Melissa officinalis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (150, 'Coriandrum sativum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (151, 'Descurainia millefolia');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (152, 'Astrantia major');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (153, 'Foeniculum vulgare');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (154, 'Isatis tinctoria');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (155, 'Erysimum scoparium');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (156, 'Bupleurum falcatum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (157, 'Ajuga reptans');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (158, 'Melittis melissophyllum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (159, 'Calendula officinalis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (160, 'Matthiola incana');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (161, 'Phlomis viscosa');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (162, 'Physalis alkekengi');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (163, 'Iberis sempervirens');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (164, 'Avena sativa');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (165, 'Petunia axillaris');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (166, 'Nicotiana rustica');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (167, 'Echinacea purpurea');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (168, 'Tagetes erecta');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (169, 'Dahlia merckii');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (170, 'Mandragora officinarum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (171, 'Athamanta cretensis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (172, 'Eupatorium cannabinum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (173, 'Teucrium chamaedrys');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (174, 'Leonurus cardiaca');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (175, 'Levisticum officinale');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (176, 'Capsicum annuum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (177, 'Bombus terrestris');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (178, 'Bunias orientalis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (179, 'Mentha x piperita');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (180, 'Erysimum cheiri');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (181, 'Bupleurum canescens var. handiense');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (182, 'Seseli libanotis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (183, 'Secale cereale');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (184, 'Stachys byzantina');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (185, 'Hordeum vulgare');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (186, 'Petroselinum crispum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (187, 'Carum carvi');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (188, 'Centaurea montana');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (189, 'Carduus defloratus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (190, 'Ocimum basilicum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (191, 'Capsicum frutescens');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (192, 'Methanosarcina mazei');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (193, 'Ephestia kuehniella');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (194, 'Ephestia elutella');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (195, 'Physalis peruviana');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (196, 'Aurinia saxatilis');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (197, 'Artemisia absinthium');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (198, 'Asclepias syriaca');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (199, 'Brassica napus');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (200, 'Artemisia abrotanum');
INSERT INTO `ncct_db`.`species` (`id`, `name`) VALUES (201, 'Triticum aestivum');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ncct_db`.`technology_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `ncct_db`;
INSERT INTO `ncct_db`.`technology_type` (`id`, `name`) VALUES (1, 'Short read');
INSERT INTO `ncct_db`.`technology_type` (`id`, `name`) VALUES (2, 'Long read');
INSERT INTO `ncct_db`.`technology_type` (`id`, `name`) VALUES (, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ncct_db`.`topical_assignment`
-- -----------------------------------------------------
START TRANSACTION;
USE `ncct_db`;
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '201-01', 'Biochemistry');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '201-02', 'Biophysics');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '201-03', 'Cell Biology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '201-04', 'Structural Biology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '201-05', 'General Genetics');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '201-06', 'Developmental Biology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '201-07', 'Bioinformatics and Theoretical Biology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '201-08', 'Anatomy');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '202-01', 'Evolution and Systematics of Plants and Fungi');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '202-02', 'Plant Ecology and Ecosystem Analysis');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '202-03', 'Inter-Organismic Interactions and Chemical Ecology of Plant Systems');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '202-04', 'Plant Physiology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '202-05', 'Plant Biochemistry and Biophysics');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '202-06', 'Plant Cell and Developmental Biology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '202-07', 'Plant Genetics');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '203-01', 'Special Zoology and Morphology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '203-02', 'Evolution, Anthropology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '203-03', 'Animal Ecology, Biodiversity and Ecosystem Research');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '203-04', 'Sensory and Behavioural Biology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '203-05', 'Biochemistry and Animal Physiology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '203-06', 'Evolutionary Cell and Developmental Biology (Zoology)');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '204-01', 'Metabolism, Biochemistry and Genetics of Microorganisms');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '204-02', 'Microbial Ecology and Applied Microbiology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '204-03', 'Medical Microbiology, Parasitology, Medical Mycology and Hygiene, Molecular Infection Biology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '204-04', 'Virology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '204-05', 'Immunology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-01', 'Epidemiology, Medical Biometry, Medical Informatics');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-02', 'Public Health, Health Services Research, Social Medicine');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-03', 'Human Genetics');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-04', 'Physiology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-05', 'Nutritional Sciences');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-06', 'Pathology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-07', 'Clinical Chemistry and Pathobiochemistry');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-08', 'Pharmacy');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-09', 'Pharmacology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-10', 'Toxicology, Occupational Medicine and Forensic Medicine');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-11', 'Anaesthesiology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-12', 'Cardiology, Angiology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-13', 'Pneumology, Clinical Infectiology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-14', 'Hematology, Oncology, Transfusion Medicine');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-15', 'Gastroenterology, Metabolism');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-16', 'Nephrology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-17', 'Endocrinology, Diabetology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-18', 'Rheumatology, Clinical Immunology, Allergology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-19', 'Dermatology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-20', 'Pediatric and Adolescent Medicine');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-21', 'Gynaecology and Obstetrics');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-22', 'Reproductive Medicine/Biology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-23', 'Urology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-24', 'Biogerontology and Geriatric Medicine');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-25', 'General and Visceral Surgery');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-26', 'Cardiothoracic and Vascular Surgery');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-27', 'Traumatology and Orthopaedics');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-28', 'Dentistry, Oral Surgery');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-29', 'Otolaryngology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-30', 'Radiology and Nuclear Medicine');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-31', 'Radiation Oncology and Radiobiology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '205-32', 'Biomedical Technology and Medical Physics');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '206-01', 'Molecular Neuroscience and Neurogenetics');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '206-02', 'Cellular Neuroscience');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '206-03', 'Developmental Neurobiology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '206-04', 'Systemic Neuroscience, Computational Neuroscience, Behaviour');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '206-05', 'Organismic Neurobiology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '206-06', 'Cognitive Neuroscience');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '206-07', 'Molecular and Cellular Neurology, Neuropathology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '206-08', 'Clinical Neurosciences I - Neurology, Neurosurgery, Neuroradiology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '206-09', 'Biological and Molecular Psychiatry');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '206-10', 'Clinical Neurosciences II - Psychiatry, Psychotherapy, Child and Adolescent Psychiatry');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '206-11', 'Clinical Neurosciences III - Ophthalmology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '207-01', 'Soil Sciences');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '207-02', 'Plant Cultivation and Agricultural Technology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '207-03', 'Plant Nutrition');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '207-04', 'Ecology of Agricultural Landscapes');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '207-05', 'Plant Breeding');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '207-06', 'Phytomedicine');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '207-07', 'Agricultural Economics and Sociology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '207-08', 'Forestry');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '207-09', 'Animal Husbandry, Breeding and Hygiene');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '207-10', 'Animal Nutrition and Nutrition Physiology');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '207-11', 'Basic Veterinary Medical Science');
INSERT INTO `ncct_db`.`topical_assignment` (`id`, `number`, `name`) VALUES (DEFAULT, '207-12', 'Basic Research on Pathogenesis, Diagnostics and Therapy and Clinical Veterinary Medicine');

COMMIT;


